### ISSUE TITLE
No module named 'correlation_cuda'

### ISSUE THREAD

**Issue by mhmtsarigul** [Tangshitao/Dense-Scene-Matching#1]
Hello, 

I try to run "python tools/video_test.py --config configs/7scenes.yaml" in Colab and I get the following error. Which Cuda version did you use? I could not find a solution.

```
Traceback (most recent call last):
  File "tools/video_test.py", line 14, in <module>
    from engine.launcher import *
  File "libs/engine/launcher.py", line 6, in <module>
    from model.arch.DSMNet import dsm_net
  File "libs/model/arch/DSMNet.py", line 5, in <module>
    from ..ops.correlation.modules.corr import (
  File "libs/model/ops/correlation/modules/corr.py", line 4, in <module>
    from ..functions.corr import correlation_op, correlation_proj_op
  File "libs/model/ops/correlation/functions/corr.py", line 3, in <module>
    import correlation_cuda
ModuleNotFoundError: No module named 'correlation_cuda'
```

Thanks for sharing your great work.

**Comment by Tangshitao** [comment]
Please compile this operation by running 
  cd libs/model/ops
  python setup.py install

**Comment by mhmtsarigul** [comment]
After installing all dependencies running "python setup.py install" solved my problem. Thanks.
